name: persoUbuntu
on: 
  workflow_dispatch:
   inputs:
     auth:
        description: 'GRDP Authorization Code'
        required: true
        default: 'paste your code here'
defaults:
  run:
    shell: bash
jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 600
    steps:
    - name: Install expect and other dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y expect
          
    - name: Download Chrome Remote Desktop
      run: |
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

    - name: Install Chrome Remote Desktop
      run: |
            sudo apt-get update
            sudo apt-get install -y ./chrome-remote-desktop_current_amd64.deb
            sudo apt-get install -f -y

    - name: Install XFCE4 and other required packages
      run: |
          sudo DEBIAN_FRONTEND=noninteractive \
          sudo apt install --assume-yes xfce4 desktop-base dbus-x11 xscreensaver

    - name: Configure Chrome Remote Desktop to use XFCE4
      run: |
          sudo bash -c 'echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
          
    - name: generate script
      run: |
           touch setup.sh
           echo "${{ github.event.inputs.auth }}" >> "setup.sh"
           chmod 777 setup.sh
           
    - name: initialize GRDP
      run: |   
           expect -c '
           spawn ./setup.sh
           expect "Enter a PIN of at least six digits: "
           send "666666\r"
           expect "Enter the same PIN again: "
           send "666666\r"
           expect eof
           '
        
    - name: Time Counter
      run: |
          curl -O https://res.cloudinary.com/dyfqshedb/raw/upload/v1727172809/loop.sh
          chmod +x loop.sh
          ./loop.sh
